version: "3.7"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./db/migrations/000001_create_items_table.up.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "3000:3000"
volumes:
  data:
